apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: backend-router
  namespace: test
spec:
  parentRefs:
    - name: book-svc
      kind: Service
      group: core
      port: 8080
  rules:
    - matches:
      - headers:
        - name: "x-backend"
          value: "test"
      backendRefs:
        - name: "book-svc-v1"
          port: 8080
    - backendRefs:
      - name: "book-svc"
        port: 8080