apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: backend-split
  namespace: test
spec:
  service: backend-a
  backends:
  - service: backend-a
    weight: 500
  - service: backend-a-v1
    weight: 500