apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-a-v1
  name: backend-a-v1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-a-v1
  template:
    metadata:
      labels:
        app: backend-a-v1
    spec:
      containers:
      - image: ghcr.io/infracloudio/backend-a:v1
        imagePullPolicy: IfNotPresent
        name: backend-a-v1
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_ENV
          value: "backend-a-v1"
        - name: HEADER
          value: "x-backend"
        - name: VERSION
          value: "new-release"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-a-v1
  name: backend-a-v1
  namespace: test
spec:
  ports:
  - name: 50051-50051
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-a-v1
  type: ClusterIP